# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openfaceservice.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'openfaceservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15openfaceservice.proto\"4\n\x05\x46rame\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\r\n\x05\x64type\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x01(\x0c\"%\n\rLandmarkTuple\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\",\n\x08Landmark\x12 \n\x08landmark\x18\x01 \x03(\x0b\x32\x0e.LandmarkTuple\"2\n\x04Gaze\x12\x14\n\x0cgaze_angle_x\x18\x01 \x01(\x02\x12\x14\n\x0cgaze_angle_y\x18\x02 \x01(\x02\"C\n\x0fLandmarkAndGaze\x12\x1b\n\x08landmark\x18\x01 \x01(\x0b\x32\t.Landmark\x12\x13\n\x04gaze\x18\x02 \x01(\x0b\x32\x05.Gaze2C\n\x0fOpenFaceService\x12\x30\n\x12GetLandmarkAndGaze\x12\x06.Frame\x1a\x10.LandmarkAndGaze\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openfaceservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAME']._serialized_start=25
  _globals['_FRAME']._serialized_end=77
  _globals['_LANDMARKTUPLE']._serialized_start=79
  _globals['_LANDMARKTUPLE']._serialized_end=116
  _globals['_LANDMARK']._serialized_start=118
  _globals['_LANDMARK']._serialized_end=162
  _globals['_GAZE']._serialized_start=164
  _globals['_GAZE']._serialized_end=214
  _globals['_LANDMARKANDGAZE']._serialized_start=216
  _globals['_LANDMARKANDGAZE']._serialized_end=283
  _globals['_OPENFACESERVICE']._serialized_start=285
  _globals['_OPENFACESERVICE']._serialized_end=352
# @@protoc_insertion_point(module_scope)
