# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: numpy.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'numpy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnumpy.proto\";\n\x0c\x41rrayRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05\x64type\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x01(\x0c\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\x0c\x32:\n\x05Numpy\x12\x31\n\x0cProcessArray\x12\r.ArrayRequest\x1a\x10.MessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'numpy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARRAYREQUEST']._serialized_start=15
  _globals['_ARRAYREQUEST']._serialized_end=74
  _globals['_MESSAGERESPONSE']._serialized_start=76
  _globals['_MESSAGERESPONSE']._serialized_end=110
  _globals['_NUMPY']._serialized_start=112
  _globals['_NUMPY']._serialized_end=170
# @@protoc_insertion_point(module_scope)
