# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openfaceservice.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'openfaceservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15openfaceservice.proto\"4\n\x05\x46rame\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\r\n\x05\x64type\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x01(\x0c\"\x1c\n\x08Landmark\x12\x10\n\x08landmark\x18\x01 \x01(\x0c\x32\x35\n\x0fOpenFaceService\x12\"\n\x0bGetLandmark\x12\x06.Frame\x1a\t.Landmark\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openfaceservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAME']._serialized_start=25
  _globals['_FRAME']._serialized_end=77
  _globals['_LANDMARK']._serialized_start=79
  _globals['_LANDMARK']._serialized_end=107
  _globals['_OPENFACESERVICE']._serialized_start=109
  _globals['_OPENFACESERVICE']._serialized_end=162
# @@protoc_insertion_point(module_scope)
